//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string Number { get; set; }
        public decimal Amount { get; set; }
        public string Type { get; set; }
        public int BonusCount { get; set; }
        public int OwnerId { get; set; }
        public bool IsOpen { get; set; }
    
        public virtual Owner Owner { get; set; }
    }
}
